const translations={
'Assistir no YouTube ↗':'Watch on YouTube ↗',
'LunaUMBRA em apresentação ao ar livre, diante da pista de dança':'LunaUMBRA performing outdoors in front of the dance floor',
'Baixar foto do LunaUMBRA ↓':'Download LunaUMBRA photo ↓','Baixar logo do LunaUMBRA ↓':'Download LunaUMBRA logo ↓',
"Dmap é um projeto de música eletrônica formado por Leo Luna (LunaUMBRA) e Freddi (Mironga), baseado em Fortaleza-CE.":"Dmap is an electronic music project formed by Leo Luna (LunaUMBRA) and Freddi (Mironga), based in Fortaleza, Brazil.",
"Pautada pela experimentação, a sonoridade do duo explora timbres analógicos e multipercussões. O estilo transita pelo progressive com vertentes dark e tech, integrando uma estética minimalista, atmosférica, intensa e programadamente imprevisível.":"Rooted in experimentation, the duo’s sound explores analog timbres and layered percussion. Their style moves through progressive with dark and tech influences, combining a minimalist, atmospheric and intense aesthetic with deliberately unpredictable structures.",
"Leo Luna e Freddi, integrantes do Dmap, diante de uma parede laranja":"Leo Luna and Freddi of Dmap in front of an orange wall",
"Baixar foto do Dmap ↓":"Download Dmap photo ↓",
"Baixar logo do Dmap ↓":"Download Dmap logo ↓",

'Álbum':'Album','Projetos':'Projects','Capas':'Artwork','Vídeos':'Video','LunaUMBRA & Dmap / Álbum':'LunaUMBRA & Dmap / Album','Duas pesquisas sonoras.':'Two approaches to sound.','Um espaço de encontro.':'A shared space.','Explorar o álbum ↓':'Explore the album ↓','DOSSIÊ DO ÁLBUM · EM DESENVOLVIMENTO':'ALBUM DOSSIER · WORK IN PROGRESS','01 / O álbum':'01 / The album','Um trabalho':'A work','em relação.':'in dialogue.',
'Optical reúne LunaUMBRA e Dmap em um mesmo álbum.':'Optical brings LunaUMBRA and Dmap together on one album.',
'Os projetos compartilham uma pesquisa em música eletrônica, com abordagens próprias de composição e construção sonora. O encontro aproxima essas identidades sem apagar suas diferenças.':'Both projects explore electronic music through distinct approaches to composition and sound. Their meeting brings these identities together while preserving their differences.',
'A experimentação em estúdio, a relação entre repetição e variação e o interesse por estruturas sonoras atravessam esse universo criativo.':'Studio experimentation, the relationship between repetition and variation, and an interest in sonic structures run through this creative practice.',
'Sobre esta apresentação':'About this presentation',
'Esta seleção reúne informações dos projetos e três estudos de capa. O texto conceitual definitivo, a história de produção, a seleção de faixas ainda serão incorporados.':'This selection brings together information about the projects and three artwork studies. The final concept text, production story and track selection will be added later.',
'02 / Os projetos':'02 / The projects',
'Projeto de música eletrônica autoral de Leo Luna, baseado em Fortaleza. A produção transita entre techno, progressive e sonoridades zenonesque, articulando atmosferas escuras, precisão sonora e impacto físico.':'LunaUMBRA is the original electronic music project of Fortaleza-based artist Leo Luna. Moving between techno, progressive and zenonesque sounds, the music combines dark atmospheres, sonic precision and physical impact.',
'O estúdio funciona como laboratório de experimentação: sintetizadores, gravação e modulação se tornam ferramentas de descoberta. Música, audiovisual e espaço fazem parte de uma mesma prática de pesquisa.':'The studio is a laboratory for experimentation: synthesizers, recording and modulation become tools for discovery. Music, audiovisual work and space are part of the same creative research.',
'Duo de música eletrônica desenvolvido por Leo Luna e Freddi. A colaboração tem uma identidade própria e compartilha parte da pesquisa sonora que também atravessa LunaUMBRA.':'Dmap is an electronic music duo formed by Leo Luna and Freddi. The collaboration has its own identity and shares some of the sonic exploration that also informs LunaUMBRA.',
'Em Optical, os dois projetos se encontram em um trabalho conjunto.':'On Optical, the two projects come together in a collaborative work.',
'03 / Pesquisa visual':'03 / Visual exploration','Três estudos.':'Three studies.','Uma identidade em construção.':'An identity taking shape.','Abra as imagens para observar os detalhes.':'Open the images to explore the details.','As opções estão identificadas pela versão do arquivo.':'Each option is labelled with its original file version.','02 / Variação':'02 / Variation','03 / Variação':'03 / Variation','04 / Variação':'04 / Variation','Baixar imagem ↓':'Download image ↓','04 / Audiovisual':'04 / Audiovisual','Clipe de Optical':'Optical music video','O clipe do álbum será disponibilizado aqui.':'The album’s music video will be available here.','Contato & materiais':'Contact & materials','Fechar ×':'Close ×','Seções':'Sections',
'Estudo de capa 02':'Artwork study 02','Estudo de capa 03':'Artwork study 03','Estudo de capa 04':'Artwork study 04','Ampliar estudo de capa 02':'Enlarge artwork study 02','Ampliar estudo de capa 03':'Enlarge artwork study 03','Ampliar estudo de capa 04':'Enlarge artwork study 04','Segunda opção de capa de Optical':'Optical artwork option 02','Terceira opção de capa de Optical':'Optical artwork option 03','Quarta opção de capa de Optical':'Optical artwork option 04'};
let language='pt';
const textNodes=[],attributes=[],walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);
while(walker.nextNode()){const node=walker.currentNode;if(translations[node.textContent.trim()])textNodes.push([node,node.textContent]);}
document.querySelectorAll('[alt],[aria-label],[data-title]').forEach(el=>['alt','aria-label','data-title'].forEach(attr=>{const value=el.getAttribute(attr);if(translations[value])attributes.push([el,attr,value]);}));
const switcher=document.createElement('div');switcher.className='language-controls';switcher.setAttribute('role','group');switcher.innerHTML='<button type="button" data-language="pt" lang="pt-BR">PT</button><button type="button" data-language="en" lang="en">EN</button>';document.querySelector('header').prepend(switcher);
function setLanguage(lang){language=lang;document.documentElement.lang=lang==='en'?'en':'pt-BR';textNodes.forEach(([node,original])=>node.textContent=lang==='en'?original.replace(original.trim(),translations[original.trim()]):original);attributes.forEach(([el,attr,original])=>el.setAttribute(attr,lang==='en'?translations[original]:original));switcher.setAttribute('aria-label',lang==='en'?'Language':'Idioma');switcher.querySelectorAll('button').forEach(button=>{const active=button.dataset.language===lang;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));});document.querySelector('meta[name="description"]').content=lang==='en'?'Optical: an album by LunaUMBRA and Dmap. Projects, sonic exploration and artwork studies.':'Optical: álbum de LunaUMBRA e Dmap. Projetos, pesquisa sonora e estudos de capa.';}
switcher.addEventListener('click',event=>{const lang=event.target.dataset.language;if(!lang)return;setLanguage(lang);const url=new URL(location.href);url.searchParams.set('lang',lang);history.replaceState(null,'',url);});
setLanguage(new URLSearchParams(location.search).get('lang')==='en'?'en':'pt');
